apiVersion: v1
kind: Service
metadata:
  name: {{ template "graylog.fullname" . }}-udp
  labels:
    app.kubernetes.io/name: {{ template "graylog.name" . }}
    helm.sh/chart: {{ template "graylog.chart" . }}
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "UDP"
spec:
  ports:
      - name: wgsyslog
      port: 55514
      protocol: UDP
      targetPort: 55514
  clusterIP:
-
